version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      tmpfs:
        - /var/lib/postgresql/data:exec,nosuid,nodev,size=512M
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: dbpassword
  keycloak:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - KC_DB=postgres
      command: start-dev --import-realm
      environment:
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=dbpassword
        - KC_HOSTNAME=localhost
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=KcAdmin1234
        - KEYCLOAK_IMPORT=/tmp/realm-export.json
      volumes:
        - ${PWD}/import:/opt/keycloak/data/import
      ports:
        - 8080:8080
      depends_on:
        - postgres
